sudo: false
language: go
go:
  - 1.6
cache:
  directories:
    - node_modules
    - "$HOME/.nvm"
    - "$HOME/.npm"
    - typings

env:
    - COMMAND=tslint
    - COMMAND=test
    - COMMAND=./server/server

install:
  - nvm install 4.0
  - touch ./package.json
  - touch ./typings.json

script:
  - make $COMMAND
