sudo: false
language: go
go:
  - 1.6
cache:
  directories:
    - node_modules
    - "$HOME/.nvm"
    - "$HOME/.npm"
    - typings
    - $GOPATH

env:
    - COMMAND=tslint
    - COMMAND=./server/server

install:
  - nvm install 4.0

script:
  - make $COMMAND
