sudo: false
language: python
python:
  - "3.5"
cache:
  pip: true
  directories:
    - node_modules
    - ENV
    - "$HOME/.nvm"
    - "$HOME/.npm"
    - typings

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
env:
  - COMMAND=tslint
  - COMMAND=pylint
  - COMMAND=test
install:
  - nvm install 4.0
script:
  - make $COMMAND
